[package]
name = 'pallet-dotmog'
version = '4.0.0-dev'
authors = ['DOT Mog Team <adming@dotmog.com>']
edition = '2018'
license = 'AGPL3.0'
homepage = 'https://www.dotmog.com'
repository = 'https://github.com/dotmog/substrate/'
description = 'FRAME pallet dmog for defining custom runtime logic.'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# third-party dependencies
codec = {default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0'}
scale-info = { version = '1.0', default-features = false, features = ['derive'] }

# primitives
sp-runtime = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/runtime" }
sp-std = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/std" }
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
node-primitives = { default-features = false, version = "2.0.0", path = "../../primitives" }

# substrate dependencies
frame-benchmarking = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/benchmarking", optional = true }
frame-support = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/support" }
frame-system = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/system" }

[dev-dependencies]
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }

[features]
default = ['std']
std = [
    'codec/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-core/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
]
runtime-benchmarks = [
	'frame-benchmarking'
]
try-runtime = [
	'frame-support/try-runtime'
]