[package]
name = 'pallet-connectfour'
version = '4.0.0-dev'
description = 'Ajuna Network pallet connect four game.'
authors = ['Ajuna Network <https://github.com/ajuna-network>']
edition = '2018'
homepage = 'https://ajuna.io'
license = 'Apache-2.0'
repository = 'https://github.com/ajuna-network/'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# external dependencies
codec = {default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0'}
scale-info = {default-features = false, features = ['derive'], version = '1.0'}

# primitives
sp-std = { default-features = false, version = '4.0.0-dev', path = "../../../../primitives/std" }
sp-runtime = { default-features = false, version = '4.0.0-dev', path = "../../../../primitives/runtime" }

# Substrate dependencies
frame-support = { default-features = false, version = '4.0.0-dev', path = "../../../../frame/support" }
frame-system = { default-features = false, version = '4.0.0-dev', path = "../../../../frame/system" }
frame-benchmarking = { default-features = false, version = '4.0.0-dev', path = "../../../../frame/benchmarking", optional = true }

# external pallets
pallet-matchmaker = {default-features = false, version = '4.0.0-dev', path = "../matchmaker" }

[dev-dependencies]
sp-core = { default-features = false, version = '4.0.0-dev', path = "../../../../primitives/core" }
sp-io = { default-features = false, version = '4.0.0-dev', path = "../../../../primitives/io" }
frame-support-test = {default-features = false, version = '3.0.0',  path = "../../../../frame/support/test" }
pallet-scheduler = { default-features = false, version = '4.0.0-dev', path = "../../../../frame/scheduler" }

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'sp-std/std',
	'sp-runtime/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
