[package]
name = 'pallet-matchmaker'
version = '4.0.0-dev'
description = 'Ajuna Network pallet matchmaker for creating matches between players.'
authors = ['Ajuna Network <https://github.com/ajuna-network>']
edition = '2018'
homepage = 'https://ajuna.io'
license = 'Apache-2.0'
repository = 'https://github.com/ajuna-network/pallet-ajuna-matchmaker/'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# external dependencies
codec = {default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0'}
scale-info = { version = '1.0', default-features = false, features = ['derive'] }

# primitives
sp-std = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/std" }

# Substrate dependencies
frame-benchmarking = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/benchmarking", optional = true }
frame-support = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/support" }
frame-system = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/system" }

[dev-dependencies]
# serde = '1.0.119'
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/runtime" }

[features]
default = ['std']
std = [
	'codec/std',
	'sp-std/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
]
runtime-benchmarks = [
	'frame-benchmarking'
]
try-runtime = [
	'frame-support/try-runtime'
]
